package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"product_service/graph/model"
)

// AddProduct is the resolver for the addProduct field.
func (r *mutationResolver) AddProduct(ctx context.Context, input model.AddProductInput) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: AddProduct - addProduct"))
}

// EditProduct is the resolver for the editProduct field.
func (r *mutationResolver) EditProduct(ctx context.Context, input model.EditProductInput) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: EditProduct - editProduct"))
}

// AddReview is the resolver for the addReview field.
func (r *mutationResolver) AddReview(ctx context.Context, input model.AddReviewInput) (*model.Review, error) {
	panic(fmt.Errorf("not implemented: AddReview - addReview"))
}

// GetProductByID is the resolver for the getProductById field.
func (r *queryResolver) GetProductByID(ctx context.Context, id string) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: GetProductByID - getProductById"))
}

// GetAllProducts is the resolver for the getAllProducts field.
func (r *queryResolver) GetAllProducts(ctx context.Context, filter *model.ProductFilter) ([]*model.Product, error) {
	panic(fmt.Errorf("not implemented: GetAllProducts - getAllProducts"))
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Health - health"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
