// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddProductInput struct {
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description *string `json:"description,omitempty"`
	Stock       int     `json:"stock"`
	SellerID    string  `json:"sellerId"`
	ImageURL    *string `json:"imageUrl,omitempty"`
}

type AddReviewInput struct {
	ProductID string `json:"productId"`
	Text      string `json:"text"`
	Rating    int    `json:"rating"`
	UserID    string `json:"userId"`
}

type EditProductInput struct {
	ProductID   string   `json:"productId"`
	Name        *string  `json:"name,omitempty"`
	Price       *float64 `json:"price,omitempty"`
	Description *string  `json:"description,omitempty"`
	Stock       *int     `json:"stock,omitempty"`
	ImageURL    *string  `json:"imageUrl,omitempty"`
}

type Mutation struct {
}

type Product struct {
	ProductID   string    `json:"productId"`
	Name        string    `json:"name"`
	Price       float64   `json:"price"`
	Description *string   `json:"description,omitempty"`
	Stock       int       `json:"stock"`
	SellerID    string    `json:"sellerId"`
	ImageURL    *string   `json:"imageUrl,omitempty"`
	Reviews     []*Review `json:"reviews"`
	CreatedAt   *string   `json:"createdAt,omitempty"`
	UpdatedAt   *string   `json:"updatedAt,omitempty"`
}

type ProductFilter struct {
	SellerID *string `json:"sellerId,omitempty"`
}

type Query struct {
}

type Review struct {
	ReviewID  string  `json:"reviewId"`
	ProductID string  `json:"productId"`
	Text      *string `json:"text,omitempty"`
	Rating    *int    `json:"rating,omitempty"`
	UserID    *string `json:"userId,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
}
